<?php

namespace AppBundle\Repository;

/**
 * AccompanimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccompanimentRepository extends \Doctrine\ORM\EntityRepository
{
}
